//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Client.Proxy.SoaTestService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SoaTestService.ISoaTestService")]
    public interface ISoaTestService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoaTestService/Operate", ReplyAction="http://tempuri.org/ISoaTestService/OperateResponse")]
        byte[] Operate(byte[] bytes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoaTestService/FacadeTestUserOperate", ReplyAction="http://tempuri.org/ISoaTestService/FacadeTestUserOperateResponse")]
        byte[] FacadeTestUserOperate(byte[] bytes);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISoaTestServiceChannel : Library.Client.Proxy.SoaTestService.ISoaTestService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SoaTestServiceClient : System.ServiceModel.ClientBase<Library.Client.Proxy.SoaTestService.ISoaTestService>, Library.Client.Proxy.SoaTestService.ISoaTestService {
        
        public SoaTestServiceClient() {
        }
        
        public SoaTestServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SoaTestServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoaTestServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoaTestServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public byte[] Operate(byte[] bytes) {
            return base.Channel.Operate(bytes);
        }
        
        public byte[] FacadeTestUserOperate(byte[] bytes) {
            return base.Channel.FacadeTestUserOperate(bytes);
        }
    }
}
